fonts: add tests for fallback font lookup w/ system ui font
...we're probably not supposed to be accessing system fonts this way.
when running the tests w/o my first fix & clearing restrictions for system font:
```
[I] ➜  ghostty git:(upstream-3) ✗ zig build test -Dtest-filter="discoverFallback"
test
└─ run ghostty-test 59/60 passed, 1 failed
error: 'font.discovery.test.coretext discoverFallback CJK codepoint' failed: 2025-09-10 13:53:31.792 ghostty-test[51978:12386835] CoreText note: Client requested name ".PingFangUITextSC-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2025-09-10 13:53:31.792 ghostty-test[51978:12386835] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
/opt/homebrew/Cellar/zig/0.14.1/lib/zig/std/testing.zig:580:14: 0x10575e86f in expect (ghostty-test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/Users/cheru/Code/ghostty/src/font/discovery.zig:1133:5: 0x10577445f in test.coretext discoverFallback CJK codepoint (ghostty-test)
    try testing.expect(face.hasCodepoint(0x4E2D, null));
    ^
error: while executing test 'os.TempDir.test_0', the following test command failed:
/Users/cheru/Code/ghostty/.zig-cache/o/d8ac3a9ccf171ecb22ca38e4e30bc420/ghostty-test --seed=0x9fe58469 --cache-dir=/Users/cheru/Code/ghostty/.zig-cache --listen=-
Build Summary: 49/51 steps succeeded; 1 failed; 59/60 tests passed; 1 failed
test transitive failure
└─ run ghostty-test 59/60 passed, 1 failed
error: the following build command failed with exit code 1:
/Users/cheru/Code/ghostty/.zig-cache/o/526a4ea34f8d95eb90ea2f3856ac80e8/build /opt/homebrew/Cellar/zig/0.14.1/bin/zig /opt/homebrew/Cellar/zig/0.14.1/lib/zig /Users/cheru/Code/ghostty /Users/cheru/Code/ghostty/.zig-cache /Users/cheru/.cache/zig --seed 0x9fe58469 -Z70fd58e5d3dc4a11 test -Dtest-filter=discoverFallback
```